### ISSUE TITLE
ASPX and Jq-SmoothScroll

### ISSUE THREAD

**Issue by dlee5400** [offthehandle/jQuery-SmoothScroll#1]
I am having trouble getting the smoothscroll to work in this environment. My page is an ASPX page and I have added your smoothscroll to a linkbutton. Here is the hookups:

```
<head>
      <link rel="stylesheet" href="Content/css/jquery.smooth.scroll.css" />
</head>

<form>
 <body>
       
       <li id="menu-item-1250" class="menu-item menu-item-type-custom menu-item-object-custom
       current-menu-item current_page_item menu-item-home menu-item-1250">
        <a href="#WhyDecroux" class="smoothScroll">Why Decroux?</a>
        </li>
                             
      <section id="WhyDecroux" class="section-features section-padding section-meta 
       onepag-section">
       </section>

       <script type='text/javascript' src="Scripts/jquery.smooth.scroll.js"></script>
 </body>
</form>

```

**Comment by offthehandle** [comment]
Did you load jQuery and instantiate Smooth Scroll? Please send me the configuration. You can see an example here: http://www.adamdelucia.com/docs/project/smooth-scroll/tutorial

**Comment by dlee5400** [comment]
Yes, i actually have at the top of the page <head> </head>

<script src="Scripts/jquery-3.3.1.js"></script> 


I get this message 

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'smoothScroll'

when I insert the following


    <script type='text/javascript' src="Scripts/jquery.smooth.scroll.js"></script>
        <script type="text/javascript">
            // Ready to call Smooth Scroll
            $(document).ready(function () {
                $.smoothScroll({
                    // Smooth Scroll configuration
                });
            });
        </script>

**Comment by dlee5400** [comment]
Is there a parameter I need to pass the .smoothScroll function?

**Comment by offthehandle** [comment]
By default all anchor tags within the body are enabled. Although you can change that to be delimited by a container or class, no parameter is required. Please show me your configuration. Also, the order of operations must be 1) jQuery, 2) Smooth Scroll, 3) Instantiation.

**Comment by offthehandle** [comment]
It's a jQuery utility. Typical setup looks like this:

```html
<script type="text/javascript" src="/Scripts/jquery.js"></script>
<script type="text/javascript" src="/Scripts/jquery.smooth.scroll.js"></script>
<script type="text/javascript">
  $(document).ready(function () {

    $.smoothScroll();
  });
</script>
```

**Comment by offthehandle** [comment]
Thanks for editing your comment to include the configuration. Today I successfully tested a fresh NuGet installation that mirrors your original code sample. Based on the JS error you're getting it sounds like you might be loading jQuery twice. Do you have a Code Pen of your source or a staging site I can debug? Also, can you provide the browser and version where you encountered the error?

**Comment by offthehandle** [comment]
Were you able to resolve  your issue with the information that I have provided or can I be of further assistance?

**Comment by dlee5400** [comment]
Sorry, yes I did.

Thank you,
David
